### ISSUE TITLE
Create view to select a type of training

### ISSUE THREAD

**Issue by Nycgia** [Nycgia/pokemon-master-training#1]
# Description
Create a view to select a type of training, showing all types with a description.

# Task
* [x] Create a simple view.
* [x] Add a main box with a title to invite to select any type of training.
* [x] Add buttons of training types with an image (a pokeball?) and a short title.
* [x] If any type is hover, the main box is changed with a description of this type.

**Comment by Nycgia** [comment]
All task are completed
