### ISSUE TITLE
Create view to select a type of training

### ISSUE THREAD

**Issue by Nycgia** [Nycgia/pokemon-master-training#2]
# Description
Add a view to select training type with buttons and a short description.

# Task
* [x] Create a simple view.
* [x] Use the main box create before.
* [x] Add a buttons with the type of training and an image.
* [x] When the buttos are in focus, displays a encouragement, demotivation or challenge text in the main box.

**Comment by Nycgia** [comment]
Issue is ended
